import 'bootstrap/dist/css/bootstrap.min.css';
import Script from 'next/script';     
import 'flag-icons/css/flag-icons.min.css';          
import 'slick-carousel/slick/slick.css';              
import 'slick-carousel/slick/slick-theme.css';        
import "./globals.css";
import Header from './components/header/Header';
import Footer from './components/footer/Footer';
import { I18nProvider } from './i18n/I18nProvider';
import ReduxProviderClient from './components/ReduxProvider/ReduxProviderClient';
import TopButton from './utils/TopButton/TopButton';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: ['/images/favicon.ico?v=4'], 
    apple:['/images/apple-touch-icon.png?v=4']
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <ReduxProviderClient>
          <I18nProvider>
            <Header />
            <main>{children}</main>
            <Footer />
            <TopButton />
          </I18nProvider>
        </ReduxProviderClient>

        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
